export const theme = {
  colors: {
    primary: "#3b82f6",
    secondary: "#64748b",
    accent: "#f59e0b",
    success: "#22c55e",
    warning: "#eab308",
    destructive: "#ef4444",
    background: "#ffffff",
    foreground: "#0f172a",
    muted: "#f1f5f9",
    mutedForeground: "#64748b",
    border: "#e2e8f0",
    input: "#e2e8f0",
    ring: "#3b82f6",
    card: "#ffffff",
    cardForeground: "#0f172a",
    popover: "#ffffff",
    popoverForeground: "#0f172a",
    primaryForeground: "#ffffff",
    secondaryForeground: "#ffffff",
    accentForeground: "#0f172a",
    destructiveForeground: "#ffffff",
  },
  dark: {
    primary: "#3b82f6",
    secondary: "#64748b",
    accent: "#f59e0b",
    success: "#22c55e",
    warning: "#eab308",
    destructive: "#ef4444",
    background: "#0f172a",
    foreground: "#f8fafc",
    muted: "#1e293b",
    mutedForeground: "#94a3b8",
    border: "#334155",
    input: "#334155",
    ring: "#3b82f6",
    card: "#0f172a",
    cardForeground: "#f8fafc",
    popover: "#0f172a",
    popoverForeground: "#f8fafc",
    primaryForeground: "#ffffff",
    secondaryForeground: "#ffffff",
    accentForeground: "#0f172a",
    destructiveForeground: "#ffffff",
  },
  radius: "0.5rem",
}

export type Theme = typeof theme